---
# vars file for adambware.homebrew-casks
casks:
  - alfred
  - atom
  - bartender
  - coda
  - cyberduck
  - firefox
  - google-chrome
  - google-cloud-sdk
  - imageoptim
  - istat-menus
  - iterm2
  - opera
  - plug
  - sequel-pro
  - skype
  - spotify
  - tower
  - transmission
  - vlc
  - qlcolorcode
  - qlstephen
  - qlmarkdown
  - quicklook-json
  - quicklook-csv
  - betterzipql
