---
# vars file for adambware.homebrew-casks
casks:
  - alfred
  - atom
  - bartender
  - boostnote
  - coda
  - cyberduck
  - dash
  - firefox
  - google-chrome
  - google-cloud-sdk
  - imageoptim
  - iterm2
  - opera
  - plug
  - private-internet-access
  - sequel-pro
  - sketch
  - skype
  - spotify
  - spotify-notifications
  - tower
  - transmission
  - transmit
  - visual-studio-code
  - vlc
  - qlcolorcode
  - qlimagesize
  - qlstephen
  - qlmarkdown
  - quicklook-json
  - quicklook-csv
